[build]
  functions = "netlify/functions"
  publish = "dist"

[functions."*"]
  timeout = 10

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8889

[functions]
 included_files = ["src/firebase.js"]

[functions.aggregateDailyMetrics]
 schedule = "0 0 * * *"